site_name: Git & GitHub
nav: 
  - Comandos: index.md
  - Crear repositorio: create_repo.md
  - Clonar repositorio: clone_repo.md
  - Areas de trabajo: working_areas.md

theme:
  name: material

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.emoji
  - attr_list
